## Loading all 3 ticker together

In [5]:
import yfinance as yf
tickers_list = ["UNH", "PFE", "MRK"]
tickers = yf.Tickers(tickers_list)
hist = tickers.download(start="2022-01-01", end="2024-12-31")

[*********************100%***********************]  3 of 3 completed

In [52]:
hist.to_csv('datasets/combined_data.csv')

## Saving the tickers into separate csv files

In [27]:
for ticker in tickers_list:
    stock = yf.Ticker(ticker)
    stock_hist = stock.history(start="2022-01-01", end="2024-12-31")
    stock_hist.to_csv(f"datasets/{ticker}.csv")

## To load a single ticker from csv

In [51]:
import pandas as pd
x = pd.read_csv("datasets/UNH.csv")
x["Date"] = pd.to_datetime(x["Date"], utc=True).dt.strftime('%d-%m-%Y') #convert to date object
x

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,03-01-2022,480.694752,483.482776,474.013083,482.886719,3033600,0.0,0.0
1,04-01-2022,483.771152,484.299904,471.926828,471.946045,3908100,0.0,0.0
2,05-01-2022,475.666621,477.810530,470.782776,470.782776,3921100,0.0,0.0
3,06-01-2022,461.466927,465.447093,445.238669,451.516541,6555200,0.0,0.0
4,07-01-2022,449.632184,449.901371,437.960903,440.893158,5494200,0.0,0.0
...,...,...,...,...,...,...,...,...
698,14-10-2024,599.109985,608.630005,597.380005,605.400024,2447100,0.0,0.0
699,15-10-2024,552.020020,569.700012,543.000000,556.289978,11939400,0.0,0.0
700,16-10-2024,557.010010,576.179993,555.119995,571.340027,5103900,0.0,0.0
701,17-10-2024,560.580017,569.469971,558.719971,566.030029,5588200,0.0,0.0
702,18-10-2024,566.849976,570.950012,563.035706,569.609985,3685858,0.0,0.0

## If for some reason u want use this csv to load 1 df only

In [53]:
y = pd.read_csv("datasets/combined_data.csv")
y

,Price,Close,Close.1,Close.2,Dividends,Dividends.1,Dividends.2,High,High.1,High.2,...,Low.2,Open,Open.1,Open.2,Stock Splits,Stock Splits.1,Stock Splits.2,Volume,Volume.1,Volume.2
0,Ticker,MRK,PFE,UNH,MRK,PFE,UNH,MRK,PFE,UNH,...,UNH,MRK,PFE,UNH,MRK,PFE,UNH,MRK,PFE,UNH
1,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-01-03 00:00:00+00:00,71.08836364746094,50.23138427734375,482.88665771484375,0.0,0.0,0.0,71.1530984410485,51.91610647656275,483.48271443752,...,474.0130231550537,70.82017462958008,51.87177230493498,480.6946910970124,0.0,0.0,0.0,9441200,57219200,3033600
3,2022-01-04 00:00:00+00:00,71.21782684326172,48.351585388183594,471.9460754394531,0.0,0.0,0.0,71.45826630897275,50.03631100844332,484.29993574772203,...,471.9268582125808,70.65370638309797,49.85010545385646,483.7711832855944,0.0,0.0,0.0,11981700,66993100,3908100
4,2022-01-05 00:00:00+00:00,72.94718170166016,49.32695007324219,470.7827453613281,0.0,0.0,0.0,73.80723372506863,50.045172405887485,477.8104990464387,...,470.7827453613281,71.44903157128401,49.51315561263317,475.66659026926266,0.0,0.0,0.0,17447900,52956400,3921100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,2024-10-14 00:00:00+00:00,109.69000244140625,29.079999923706055,605.4000244140625,0.0,0.0,0.0,110.06999969482422,29.170000076293945,608.6300048828125,...,597.3800048828125,109.43000030517578,29.15999984741211,599.1099853515625,0.0,0.0,0.0,8130700,23594200,2447100
701,2024-10-15 00:00:00+00:00,111.52999877929688,29.440000534057617,556.2899780273438,0.0,0.0,0.0,111.58000183105469,29.739999771118164,569.7000122070312,...,543.0,109.95999908447266,29.09000015258789,552.02001953125,0.0,0.0,0.0,9109500,29009900,11939400
702,2024-10-16 00:00:00+00:00,110.41999816894531,29.670000076293945,571.3400268554688,0.0,0.0,0.0,111.19999694824219,29.81999969482422,576.1799926757812,...,555.1199951171875,111.0,29.5,557.010009765625,0.0,0.0,0.0,8729200,28414800,5103900
703,2024-10-17 00:00:00+00:00,109.75,29.270000457763672,566.030029296875,0.0,0.0,0.0,110.19000244140625,29.530000686645508,569.469970703125,...,558.719970703125,110.13999938964844,29.479999542236328,560.5800170898438,0.0,0.0,0.0,8513200,23747500,5588200
704,2024-10-18 00:00:00+00:00,108.69999694824219,29.219999313354492,569.6099853515625,0.0,0.0,0.0,109.75,29.364999771118164,570.9500122070312,...,563.0357055664062,109.9000015258789,29.299999237060547,566.8499755859375,0.0,0.0,0.0,9519439,24055814,3685858